app.property.spring-name=videorentalsystem

# Database Config
spring.datasource.driver-class-name=${DB_DRIVER_CLASS:com.microsoft.sqlserver.jdbc.SQLServerDriver}
spring.datasource.hibernate.dialect=${DB_HIBERNATE:org.hibernate.dialect.MySQL8Dialect}
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# App Config
